name: rick_morty_app
description: "Rick and Morty Character Catalog"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.3
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.9

flutter:
  uses-material-design: true